### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by rgbkrk** [willwhitney/hydrogen#1]
Hey there,

Just wanted to say that this is *awesome*. I'm so glad someone started this up. I was waiting on the Big Split :tm: to settle before starting this up so I'm glad you took the initiative to kick this off. I'm assuming since I'm running from `master` on all the Jupyter repos that this isn't quite in the state to work with the coming release of the split off Jupyter and IPython packages. Currently I'm seeing the display waiting on output:

![screenshot 2015-05-17 22 18 09](https://cloud.githubusercontent.com/assets/836375/7673983/0b088eb0-fce3-11e4-91ef-666aebad5a17.png)

![screenshot 2015-05-17 22 22 08](https://cloud.githubusercontent.com/assets/836375/7673988/23186b56-fce3-11e4-804d-ceb45427c980.png)

Since you're down the same path, I might as well mention a few bits of interest. The comms channels for IPython widgets are going to be wonderful to use though we'll end up needing them decoupled from the Notebook:

https://github.com/ipython/ipywidgets/issues/13

We'll likely need `zmq` to bring in the latest `nan` to stay up to date with `iojs`. I ran into this while tinkering with an Electron app to display output alongside a console.

https://github.com/JustinTulloss/zeromq.node/pull/420 / https://github.com/JustinTulloss/zeromq.node/pull/421

I've noticed a couple deprecations, but I'll ship a PR your way shortly.

**Comment by rgbkrk** [comment]
Forgot to mention, I poked the IJavascript developer to extract the messaging protocol into a separate package as [jmp (Jupyter Messaging Protocol)](https://github.com/n-riesco/jmp). It would be nice to share some common ground there.

**Comment by rgbkrk** [comment]
Well, not surprisingly I was in a weird state from master that I figured out by dumping errors from when the kernel is booted. Now I get at least a check mark but no output.

![screenshot 2015-05-17 23 06 22](https://cloud.githubusercontent.com/assets/836375/7674291/68cb496a-fce9-11e4-9e31-1dbdf68d74ca.png)

**Comment by willwhitney** [comment]
Thanks! I really appreciate the support.

This is tested against the release builds of everything, not the upcoming Big Split versions. Like you, I'm waiting for the dust to settle a little before making those changes :) Hydrogen will need to keep supporting the pre-Split versions for a while, but it would be great to get a branch going to get ready for it.

Widgets are going to be great — I haven't looked into implementation for them at all yet.

[io.js is getting merged back into node](https://github.com/nodejs/node), so that may make things easier.

Totally on board with the idea of a shared codebase with `jmp` — I'll look into switching over to it. It would be great to have other people helping cover all the weird edge cases and faulty implementations of various kernels.

**Comment by rgbkrk** [comment]
Oops! I should have reported back that it now works beautifully after getting everything setup with current master. Hydrogen does work with IPython 3.1.x and the future release (at the moment).

**Comment by willwhitney** [comment]
Awesome! Thanks for the report.
