### ISSUE TITLE
Very long one-line output overlays code

### ISSUE THREAD

**Issue by dlfivefifty** [willwhitney/hydrogen#103]
In Julia, evaluating

println("hellodgiofppfdiodskvl;fskg;slgkfsd'kgfls;kgfdl;'dgdffdipdidfopfddiopfifopdsifopiifopdsdsopfdiop")

will overlay the text, making it unreadable.

**Comment by beardicus** [comment]
This happens to me with javascript too. I think it'd be fine to hard wrap it and present it as a multiline-result, perhaps with some glyph that indicates each hard-wrap point. An alternative would be to keep it a single-line result, but make it horizontally scrollable.

**Comment by terraqout** [comment]
Scrolling preferred, I think.

**Comment by willwhitney** [comment]
Last time I looked into this, it wasn't possible to scroll one of these marker decorations (otherwise I'd have the multiline ones scroll vertically, too).

Does one of you want to write a PR for this? It would be awesome to have someone rework [ResultView](https://github.com/willwhitney/hydrogen/blob/master/lib/result-view.coffee) a little bit. The two changes would be:

1. Add wrapping in [Less](https://github.com/willwhitney/hydrogen/blob/master/styles/hydrogen.less).
2. Change the logic of ResultView to make a bubble single- or multi-line based on its measure size (<= or > line height) instead of based on the content inside.

**Comment by willwhitney** [comment]
Also if that person would check and see if scrolling these is possible now, that would be sweet.

**Comment by terraqout** [comment]
@willwhitney I'll do it. When have free time for that.

**Comment by terraqout** [comment]
please review #136
