### ISSUE TITLE
Result view indentation

### ISSUE THREAD

**Issue by terraqout** [willwhitney/hydrogen#117]
This is easy examples of broken indentation, but they break some tables in julia too:
![in javascript](https://cloud.githubusercontent.com/assets/1011721/10175931/702151ac-66fa-11e5-8c21-4d1417b99903.png)
![in julia](https://cloud.githubusercontent.com/assets/1011721/10175933/719abb9a-66fa-11e5-9670-a7101286a3b9.png)

So what this magic space about:
https://github.com/willwhitney/hydrogen/blob/master/lib/result-view.coffee#L131-L134

**Comment by stevengj** [comment]
Yes, I just noticed the "magic space" too and was about to file an issue.  It seems like it would be better if it didn't insert spaces.

Note that IJulia has an asynchronous task reading stdout and sending `stream` messages, so it will tend to send stdout as multiple `stream` messages rather than just one.

**Comment by willwhitney** [comment]
I assume in some early version of Hydrogen one of the kernels was smashing words together without the space. This doesn't seem to be an issue anymore, so I'll remove the space.
