### ISSUE TITLE
Write to console?

### ISSUE THREAD

**Issue by amandabee** [willwhitney/hydrogen#129]
Not sure if this is a documentation request or a feature request but ... I'm launching atom with `atom path/to/whatever.py` and trying to figure out how I'd write something back to a console somewhere. I read https://github.com/willwhitney/hydrogen/issues/52 which seems to hint that I ought to have an ipython shell someplace that Hydrogen is writing to? 

If I run `console.log("something")` I get "console is not defined":

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-37-28f94e59b0d7> in <module>()
----> 1 console.log("Something")
NameError: name 'console' is not definedNameError
name 'console' is not defined
```

I'm sure I'm missing a step or six here, in which case I'd love to help clarify the documentation!

**Comment by willwhitney** [comment]
Looks like you're running that code with Hydrogen, correct? It's interpreting it as Python code (because you're in a Python file). Using `print` just like normal in Python should show you output in a Hydrogen bubble.

If what you're going for is to actually get some output streaming into your terminal, there's not a great way to do that inside of Hydrogen. However, since this is Unix, there's an easy Unix-ey way to do it: make a temporary file with Python that you `f.write` to in your code, then `tail -F` that file in the terminal.

Please let me know what I can do to make the documentation clearer — or even better, send a PR!

**Comment by amandabee** [comment]
Yes, Python, sorry! 

In this particular case, I have a list of dictionaries, called `all_filings` -- if I run print(all_filings[1]['format']) I can see the output, but there's no way to copy it. And it's a long line so it obscures my code until I clear results.

If I run
```
for filing in all_filings:
    print filing['format']
```

I get a block in a hydrogen bubble that I can copy or open in a new document. It seems weird that I can't copy the results of `print` but I can copy the results of a loop that does nothing but print. 

`f.write` is a good work around for the moment, though.

**Comment by willwhitney** [comment]
If the output is multiple lines, Hydrogen shows the options for copy, etc.
It's kind of a hack, but usually it works OK. If there's a better way to
handle the tension between quick, short outputs that should be inline and
bigger ones that need to be broken out, I'd love to know about it!
