### ISSUE TITLE
Allow configuration of paths to dependent programs so we don't need to run atom from the terminal?

### ISSUE THREAD

**Issue by radix** [willwhitney/hydrogen#71]
I think running Atom as an app could work if there were configurable options for the location of necessary binaries

**Comment by willwhitney** [comment]
Actually, some kernels (e.g. Julia) already work without the `$PATH`. Hydrogen goes and finds where the kernels are listed, and those kernelspecs contain the instructions for running the kernel, so kernels that contain fully-qualified paths work no matter what.

You can fix any kernels that don't use fully-qualified paths by modifying the kernelspecs (probably in `~/.ipython/kernels/` or `/usr/local/share/jupyter/`) to contain fully-qualified paths (`/usr/local/bin/node` instead of `node`). You'll also need to create a kernelspec for Python by running `ipython kernelspec install-self`; the Python one uses a fully-qualified path already.

This is kind of a pain, and probably those kernels should just be doing this already. The good news is that all the kernels are open-source and you can send them a pull request to fix it!

However, updates and installation are still going to need the `$PATH`, because I can't control how `npm` installs things (especially `zmq`).

**Comment by radix** [comment]
@willwhitney The problem is that Atom can't even find my IPython without running from the shell, because I don't have IPython installed system-wide. I would at least like for Hydrogen to offer a configurable IPython command. This is separate from IPython finding commands for running its subprocesses.

**Comment by willwhitney** [comment]
Hydrogen doesn't use IPython at all. It starts the kernels itself and is a
replacement for the IPython notebook server.

The only time it uses the `ipython` command is when starting a Python
kernel, and you can avoid that by installing the Python kernelspec as
stated above.

**Comment by radix** [comment]
@willwhitney Oh, I totally misunderstood. Thank you. Sorry, this is my first time ever using Jupyter, so I wasn't familiar with all this kernel business. It turns out `install-self` installed some crap system-wide :-( but I was able to then move `/usr/local/share/jupyter/kernels` to `~/.ipython/kernels` to disinfect my system and Hydrogen is now working great when run from the desktop. Thanks :-)

**Comment by willwhitney** [comment]
No worries! Glad I could help.
